In [1]:
import numpy as np

In [2]:
ar = np.arange(30)

In [3]:
ar2 = ar.reshape(3,10)

In [4]:
ar2.shape

(3, 10)

In [7]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [8]:
import pandas as pd

In [9]:
df = pd.DataFrame(ar2, columns=list("abcdefghij"))

In [10]:
df

a   b   c   d   e   f   g   h   i   j
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29

In [11]:
help(df.add)

Help on method add in module pandas.core.ops:

add(other, axis='columns', level=None, fill_value=None) method of pandas.core.frame.DataFrame instance
    Get Addition of dataframe and other, element-wise (binary operator `add`).
    
    Equivalent to ``dataframe + other``, but with support to substitute a fill_value
    for missing data in one of the inputs. With reverse version, `radd`.
    
    Among flexible wrappers (`add`, `sub`, `mul`, `div`, `mod`, `pow`) to
    arithmetic operators: `+`, `-`, `*`, `/`, `//`, `%`, `**`.
    
    Parameters
    ----------
    other : scalar, sequence, Series, dict or DataFrame
        Any single or multiple element data structure, or list-like object.
    axis : {0 or 'index', 1 or 'columns'}
        Whether to compare by the index (0 or 'index') or columns.
        (1 or 'columns'). For Series input, axis to match Series index on.
    level : int or label
        Broadcast across a level, matching Index values on the
        passed MultiIndex l

In [13]:
df

a   b   c   d   e   f   g   h   i   j
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29

In [12]:
df.add(df, axis='columns')

a   b   c   d   e   f   g   h   i   j
0   0   2   4   6   8  10  12  14  16  18
1  20  22  24  26  28  30  32  34  36  38
2  40  42  44  46  48  50  52  54  56  58

In [14]:
df.add(df, axis='index')

a   b   c   d   e   f   g   h   i   j
0   0   2   4   6   8  10  12  14  16  18
1  20  22  24  26  28  30  32  34  36  38
2  40  42  44  46  48  50  52  54  56  58

In [15]:
df = pd.DataFrame(
    {'name': ['KIM', 'LEE', 'SMITH','BROWN', 'MILLER'],
     'age': [24, 32, 43, 24, np.nan],
     'height': [178, 168, 171, 185, 176],
     'sex': ['M', 'F', 'F', 'M', 'F']})
df

name   age  height sex
0     KIM  24.0     178   M
1     LEE  32.0     168   F
2   SMITH  43.0     171   F
3   BROWN  24.0     185   M
4  MILLER   NaN     176   F

In [16]:
df.drop([1,2], axis=0)

name   age  height sex
0     KIM  24.0     178   M
3   BROWN  24.0     185   M
4  MILLER   NaN     176   F

In [19]:
help(df.mean)

Help on method mean in module pandas.core.generic:

mean(axis: 'int | None | lib.NoDefault' = <no_default>, skipna=True, level=None, numeric_only=None, **kwargs) method of pandas.core.frame.DataFrame instance
    Return the mean of the values over the requested axis.
    
    Parameters
    ----------
    axis : {index (0), columns (1)}
        Axis for the function to be applied on.
        For `Series` this parameter is unused and defaults to 0.
    skipna : bool, default True
        Exclude NA/null values when computing the result.
    level : int or level name, default None
        If the axis is a MultiIndex (hierarchical), count along a
        particular level, collapsing into a Series.
    
        .. deprecated:: 1.3.0
            The level keyword is deprecated. Use groupby instead.
    numeric_only : bool, default None
        Include only float, int, boolean columns. If None, will attempt to use
        everything, then use only numeric data. Not implemented for Series.
  

In [20]:
df[['age', 'height']]

age  height
0  24.0     178
1  32.0     168
2  43.0     171
3  24.0     185
4   NaN     176

In [17]:
df[['age', 'height']].mean(axis=0)

age        30.75
height    175.60
dtype: float64

In [18]:
df[['age', 'height']].mean(axis=1)

0    101.0
1    100.0
2    107.0
3    104.5
4    176.0
dtype: float64

In [21]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [24]:
ar.data

In [25]:
import collections.abc as abc

In [27]:
issubclass(np.ndarray,abc.MutableSequence)

False

In [28]:
issubclass(np.ndarray,abc.Sequence)

False

In [30]:
abc.MutableSequence.__abstractmethods__

frozenset({'__delitem__', '__getitem__', '__len__', '__setitem__', 'insert'})

In [33]:
dir(np.ndarray)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

## 변경불가 처리 

In [36]:
a = np.arange(10)
a.flags.writeable = False

In [35]:
a[0] = 1

ValueError: assignment destination is read-only

In [39]:
b = np.add(a,a)

In [40]:
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [41]:
b[0] = 100

In [42]:
b

array([100,   2,   4,   6,   8,  10,  12,  14,  16,  18])

In [43]:
b.data

In [44]:
b+= a

In [45]:
b

array([100,   3,   6,   9,  12,  15,  18,  21,  24,  27])

In [46]:
a+a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [47]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:

# ndarray 객체를 생성합니다.
arr = np.array([1, 2, 3])

# ndarray 객체의 실제 데이터에 직접 액세스합니다.
print(arr.data)
#<memory at 0x15350cf40>

# ndarray 객체의 실제 데이터를 다른 객체로 변환합니다.
list_arr = arr.data.tolist()
print(list_arr)
# [1, 2, 3]

[1, 2, 3]


In [ ]:
isinstance(arr.data, memoryvie