# 1. 배열



## 1-1 배열 

In [16]:
import array

# 배열 생성 (타입 'i'는 정수형을 나타냄)
my_array = array.array('i', [1, 2, 3, 4, 5])

# 배열 출력
print("Original Array:", my_array)

# 배열에 요소 추가
my_array.append(6)
print("After Appending:", my_array)

# 배열 요소 변경
my_array[2] = 10
print("After Modifying:", my_array)

# 배열 요소 삭제 (인덱스 3의 요소 삭제)
del my_array[3]
print("After Deleting:", my_array)


Original Array: array('i', [1, 2, 3, 4, 5])
After Appending: array('i', [1, 2, 3, 4, 5, 6])
After Modifying: array('i', [1, 2, 10, 4, 5, 6])
After Deleting: array('i', [1, 2, 10, 5, 6])


## 1-2 다차원 배열 

In [17]:
import numpy as np

# 1차원 배열 생성
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1)

# 2차원 배열 생성
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print(arr2)

# 배열 정보 출력
print("Shape of arr2:", arr2.shape)
print("Data Type of arr2:", arr2.dtype)

# 배열 연산
arr3 = arr1 * 2
print("Multiplying 1D Array by 2:")
print(arr3)

# 배열 슬라이싱
print("Slicing arr2:")
print(arr2[1, :])  # 두 번째 행 출력

# 배열 연산 (브로드캐스팅)
arr4 = arr2 + 10
print("Adding 10 to arr2:")
print(arr4)

# 통계 연산
mean_value = np.mean(arr2)
print("Mean of arr2:", mean_value)


1D Array:
[1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]]
Shape of arr2: (2, 3)
Data Type of arr2: int64
Multiplying 1D Array by 2:
[ 2  4  6  8 10]
Slicing arr2:
[4 5 6]
Adding 10 to arr2:
[[11 12 13]
 [14 15 16]]
Mean of arr2: 3.5


## 2. 자료구조

## 2-1 스택 

In [2]:
stack = []
stack.append(1)  # 요소를 스택에 추가
stack.append(2)
top_element = stack.pop()  # 스택에서 요소를 꺼내기


In [3]:
from collections import deque

stack = deque()
stack.append(1)
stack.append(2)
top_element = stack.pop()


## 2-2 큐

In [4]:
queue = []
queue.append(1)  # 요소를 큐에 추가
queue.append(2)
front_element = queue.pop(0)  # 큐에서 요소를 꺼내기


In [5]:
from collections import deque

queue = deque()
queue.append(1)
queue.append(2)
front_element = queue.popleft()


## 2-3 deque

In [1]:
from collections import deque

# 빈 deque 생성
my_deque = deque()

# 양 끝에 요소 추가
my_deque.append(1)  # 오른쪽 끝에 1 추가
my_deque.appendleft(2)  # 왼쪽 끝에 2 추가

# deque 출력
print(my_deque)  # deque([2, 1])

# 양 끝에서 요소 제거
my_deque.pop()  # 오른쪽 끝 요소 제거
my_deque.popleft()  # 왼쪽 끝 요소 제거

# deque 출력
print(my_deque)  # deque([])

# 여러 요소를 한 번에 추가
my_deque.extend([3, 4, 5])  # 오른쪽 끝에 [3, 4, 5] 추가
my_deque.extendleft([2, 1])  # 왼쪽 끝에 [2, 1] 추가

# deque 출력
print(my_deque)  # deque([1, 2, 3, 4, 5])


deque([2, 1])
deque([])
deque([1, 2, 3, 4, 5])


## 2-4 Queue 모듈 사용 

In [6]:
import queue

q = queue.Queue()
q.put(1)
q.put(2)
front_element = q.get()


In [7]:
import queue

stack = queue.LifoQueue()
stack.put(1)
stack.put(2)
top_element = stack.get()


## 2-5 링크드리스트

In [9]:
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, data):
        new_node = Node(data)
        if not self.head:
            self.head = new_node
        else:
            current = self.head
            while current.next:
                current = current.next
            current.next = new_node

    def display(self):
        current = self.head
        while current:
            print(current.data, end=" -> ")
            current = current.next
        print("None")

# 링크드 리스트 생성
my_linked_list = LinkedList()

# 요소 추가
my_linked_list.append(1)
my_linked_list.append(2)
my_linked_list.append(3)



In [10]:
# 링크드 리스트 출력
my_linked_list.display()

1 -> 2 -> 3 -> None


## 2-6 리스트 재귀호출 

In [14]:
def process_list(lst):
    # 재귀 호출을 멈추는 조건: 빈 리스트인 경우
    if not lst:
        return
    
    # head (첫 번째 요소) 추출 및 처리
    head = lst[0]
    print("Head:", head, end="  ")
    
    # tail (나머지 요소)을 재귀 호출로 처리
    tail = lst[1:]
    print("Tail:", tail)
    
    process_list(tail)


In [15]:
# 테스트용 리스트
my_list = [1, 2, 3, 4, 5]

# 리스트 처리 시작
process_list(my_list)

Head: 1  Tail: [2, 3, 4, 5]
Head: 2  Tail: [3, 4, 5]
Head: 3  Tail: [4, 5]
Head: 4  Tail: [5]
Head: 5  Tail: []
